<a href="https://colab.research.google.com/github/nike-2001/numpy/blob/main/Copy_of_More_Numpy_Methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Padding with Different Pad Widths

* `numpy.pad(array, pad_width, mode='constant', **kwargs)`
  * `pad_width` is the number of values padded to the edges of each axis.
  * Output is padded array of rank equal to `array`, with shape increased according to `pad_width`. 


In [2]:
array_2D = np.array([['A', 'B', 'C'], 
                  ['D', 'E', 'F'],
                  ['G', 'H', 'I']])

Padding with 'constant' mode

In [3]:
np.pad(array_2D, pad_width=((1, 2),(3, 1)), mode='constant', constant_values=(('X', 'Y'),('W', 'Z')))

array([['W', 'W', 'W', 'X', 'X', 'X', 'Z'],
       ['W', 'W', 'W', 'A', 'B', 'C', 'Z'],
       ['W', 'W', 'W', 'D', 'E', 'F', 'Z'],
       ['W', 'W', 'W', 'G', 'H', 'I', 'Z'],
       ['W', 'W', 'W', 'Y', 'Y', 'Y', 'Z'],
       ['W', 'W', 'W', 'Y', 'Y', 'Y', 'Z']], dtype='<U1')

Pad with 'edge' mode

In [4]:
np.pad(array_2D, ((1, 2),(3, 1)), 'edge')

array([['A', 'A', 'A', 'A', 'B', 'C', 'C'],
       ['A', 'A', 'A', 'A', 'B', 'C', 'C'],
       ['D', 'D', 'D', 'D', 'E', 'F', 'F'],
       ['G', 'G', 'G', 'G', 'H', 'I', 'I'],
       ['G', 'G', 'G', 'G', 'H', 'I', 'I'],
       ['G', 'G', 'G', 'G', 'H', 'I', 'I']], dtype='<U1')

# More Numpy Methods

### **`np.unique`**



*   `np.unique(arr, return_index=False, return_inverse=False, return_counts=False, axis=None)`
  *   Returns the sorted unique elements of an array.



In [5]:
a = np.array([1, 3, 3, 1, 2, 1])
np.unique(a)

array([1, 2, 3])

* If `return_index = True`, it returns the indices of the first occurrences of the unique values in the original array, along with the unique sorted array.

In [6]:
unique_array, first_indices = np.unique(a, return_index = True)
unique_array, first_indices

(array([1, 2, 3]), array([0, 4, 1]))

* If `return_counts = True`, it returns the number of times each of the unique values comes up in the original array. 

In [7]:
a = np.array([1, 3, 3, 1, 2, 1])
np.unique(a, return_counts = True)

(array([1, 2, 3]), array([3, 1, 2]))

The following code returns the unique rows of a 2D array:

In [8]:
a = np.array([[1, 2, 1],
              [1, 2, 1],
              [3, 2, 4]])

np.unique(a, axis=0)

array([[1, 2, 1],
       [3, 2, 4]])

* If `return_inverse = True`, it returns the indices to reconstruct the original array from the unique array.

In [9]:
a = np.array([1, 3, 3, 1, 2, 1])
unique_array, indices = np.unique(a, return_inverse = True)

print("original array:\n ", a, "\n")
print("indices:\n", indices, "\n" )
print("reconstructed original array using fancy indexing:\n", unique_array[indices])

original array:
  [1 3 3 1 2 1] 

indices:
 [0 2 2 0 1 0] 

reconstructed original array using fancy indexing:
 [1 3 3 1 2 1]


### **`np.where`**

* `numpy.where(condition[, x, y])`
  * For all the elements where the condition is `True`, the returned array has the corresponding elements chosen from `x`. 
  * For all the elements where the condition is `False`, the returned array has the corresponding elements chosen from `y`.

In [10]:
np.where?

In [11]:
a = np.arange(5)
np.where(a > 2, [11, 12, 13, 14, 15], [111, 222, 333, 444, 555])

array([111, 222, 333,  14,  15])

In [12]:
a = np.arange(10)
np.where(a > 7, 0, 100)

array([100, 100, 100, 100, 100, 100, 100, 100,   0,   0])

In [13]:
a = np.arange(10)
np.where(a > 5, a*2, a*a)

array([ 0,  1,  4,  9, 16, 25, 12, 14, 16, 18])

In [14]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

np.where(a < 5, a , 0)

array([[1, 2, 3],
       [4, 0, 0]])

**Comparison can also be done between two different arrays**

In [15]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.ones([2, 3]) * 4

print("a: \n", a, "\n")
print("b: \n", b, "\n")

print("np.where result:\n", np.where(a < b, a , 0))

a: 
 [[1 2 3]
 [4 5 6]] 

b: 
 [[4. 4. 4.]
 [4. 4. 4.]] 

np.where result:
 [[1 2 3]
 [0 0 0]]


**When the two arrays are of different shapes, they are broadcast together before applying the operation**

In [16]:
x = np.array([[0],
              [1],
              [2]])

y = np.array([[3, 4, 5, 6]])

np.where(x < y, x, 10 + y)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

### **`np.any`**

* `numpy.any(a, axis=None)`
  * Tests whether **any** of the array elements along the given `axis` evaluates to `True`.
  * Returns a new boolean ndarray.

In [17]:
a = np.array([False, True, True, False])
np.any(a)

True

In [18]:
a = np.array([1, 0, 0, 2])
np.any(a)

True

In [19]:
a = np.array([0, 0, 0, 0])
np.any(a)

False

In [20]:
a = np.array([[1, 0, 3, 4],
              [2, 0, 6, 5]])

resultant_array_0 = np.any(a, axis=0)
print("resultant array along axis 0:\n",resultant_array_0,"\n")

resultant_array_1 = np.any(a, axis=1)
print("resultant array along axis 1:\n",resultant_array_1,"\n")

resultant_array_none = np.any(a)
print("resultant array along axis none:\n",resultant_array_none,"\n")

resultant array along axis 0:
 [ True False  True  True] 

resultant array along axis 1:
 [ True  True] 

resultant array along axis none:
 True 



### **`np.all`**



*   `numpy.all(a, axis=None, out=None)`
  *   Tests whether **all** of the array elements along the given `axis` evaluate to `True`.
  *   Returns a new boolean ndarray.



In [21]:
a = np.array([1, 2, 3, 0])

result_any = np.any(a)
result_all = np.all(a)

print("result using any:\n", result_any, "\n")
print("result using all:\n", result_all, "\n")

result using any:
 True 

result using all:
 False 



In [22]:
a = np.array([[1, 0, 3, 4],
              [2, 0, 6, 5]])

resultant_array_0 = np.all(a, axis=0)
print("resultant_array_along_axis_0:\n",resultant_array_0,"\n")

resultant_array_1 = np.all(a, axis=1)
print("resultant_array_along_axis_1:\n",resultant_array_1,"\n")

resultant_array_none = np.all(a)
print("resultant_array_along_axis_none:\n",resultant_array_none,"\n")

resultant_array_along_axis_0:
 [ True False  True  True] 

resultant_array_along_axis_1:
 [False False] 

resultant_array_along_axis_none:
 False 



### **np.nan**

* `numpy.nan` 
  * IEEE 754 floating point representation of **N**ot **a** **N**umber(NaN).

In [23]:
a = np.array([0]) / 0
a

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan])

**We can not compare two NaNs**

In [24]:
np.nan == np.nan

False

### **np.inf**

* `numpy.inf` 
  * IEEE 754 floating point representation of **(positive) infinity**.

In [25]:
a = np.array([1]) / 0
a

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf])

Comparing two inf numbers.

In [26]:
np.inf == np.inf

True